# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-07 15:49
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='invitation',
            managers=[
                ('eobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='transfer',
            managers=[
                ('eobjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
